name: CI Lint Types

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm ci
    - name: Generate types
      run: npm start
    - name: Lint types
      id: lint
      run: npm run lint
      env:
        GAPI_MAX_PARALLEL: 3
    - name: Copy discovery service response JSON
      if: failure()
      run: cp .tmp/${{ env.FAILED_TYPE }}.json types/${{ env.FAILED_TYPE }}
    - name: Upload failed type
      uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: ${{ env.FAILED_TYPE }}
        path: types/${{ env.FAILED_TYPE }}
